# Generated by Django 5.2.7 on 2025-11-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tag_remove_article_update_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
