# Generated by Django 5.2.7 on 2025-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_article_tags_delete_articletag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='webapp.tag', verbose_name='Теги'),
        ),
    ]
